<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>repoctl</AssemblyName>
    <PackAsTool>true</PackAsTool>
    <PackageId>Altinn.Authorization.RepoCtl</PackageId>
    <ToolCommandName>$(AssemblyName)</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Nerdbank.Streams" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Altinn.Authorization.RepoCtl.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../pkgs/Altinn.Authorization.CommandLine/src/CommandLine.GitHub.Actions/Altinn.Authorization.CommandLine.GitHub.Actions.csproj" />
    <ProjectReference Include="../../../../pkgs/Altinn.Authorization.CommandLine/src/CommandLine.Shell/Altinn.Authorization.CommandLine.Shell.csproj" />
    <ProjectReference Include="../../../../pkgs/Altinn.Authorization.CommandLine/src/CommandLine/Altinn.Authorization.CommandLine.csproj" />
    <ProjectReference Include="../../../../pkgs/Altinn.Authorization.RepoCtl/src/RepoCtl.Model/Altinn.Authorization.RepoCtl.Model.csproj" />
  </ItemGroup>

</Project>
