on:
  push:
    branches:
      - main

name: release-please

env:
  # renovate: datasource=nuget depName=Altinn.Authorization.RepoCtl
  repoctlVersion: "1.2.0"

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Log release output
        env:
          RELEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: 'echo "Release output: $RELEASE_OUTPUT"'

    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      full: ${{ toJSON(steps.release.outputs) }}

  publish:
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.release_created == 'true'
    needs:
      - release-please

    permissions:
      contents: write

    strategy:
      matrix:
        path: ${{fromJson(needs.release-please.outputs.paths_released)}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ format('refs/tags/{0}', fromJSON(needs.release-please.outputs.full)[format('{0}--tag_name', matrix.path)]) }}

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Install RepoCtl
        run: |
          dotnet tool install --global Altinn.Authorization.RepoCtl --version "${{ env.repoctlVersion }}"
          
          repoctl --version

      - name: Build
        working-directory: ${{ matrix.path }}
        run: dotnet build -c Release

      - name: Test
        run: repoctl vertical test "${{ matrix.path }}" -- -c Release --no-build

      - name: Pack
        run: repoctl vertical pack "${{ matrix.path }}" -- -c Release --no-build

      - name: Create artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ format('release-{0}', fromJSON(needs.release-please.outputs.full)[format('{0}--id', matrix.path)]) }}
          path: artifacts/**/*.nupkg
          if-no-files-found: error
          retention-days: 3

      - name: Upload packages to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES_GLOB: artifacts/**/*.nupkg
          RELEASE_ID: ${{ fromJSON(needs.release-please.outputs.full)[format('{0}--id', matrix.path)] }}
        run: repoctl github upload ${RELEASE_ID} "${FILES_GLOB}"

  publish-github-packages:
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.release_created == 'true'
    needs:
      - release-please
      - publish

    permissions:
      contents: read   # required for checkout
      actions: read    # required for download-artifact
      packages: write  # required for publishing to GitHub Packages

    strategy:
      matrix:
        path: ${{fromJson(needs.release-please.outputs.paths_released)}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ format('refs/tags/{0}', fromJSON(needs.release-please.outputs.full)[format('{0}--tag_name', matrix.path)]) }}

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Install RepoCtl
        run: |
          dotnet tool install --global Altinn.Authorization.RepoCtl --version "${{ env.repoctlVersion }}"
          
          repoctl --version

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ format('release-{0}', fromJSON(needs.release-please.outputs.full)[format('{0}--id', matrix.path)]) }}
          path: artifacts

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES_GLOB: artifacts/**/*.nupkg
        run: |
          dotnet nuget add source --username Altinn --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Altinn/index.json"
          repoctl nuget publish "${FILES_GLOB}" -- --api-key "${GITHUB_TOKEN}" --source "github"

  publish-nuget:
    runs-on: ubuntu-latest
    environment: nuget
    if: needs.release-please.outputs.release_created == 'true'
    needs:
      - release-please
      - publish-github-packages

    permissions:
      contents: read   # required for checkout
      actions: read    # required for download-artifact
      id-token: write  # required for OIDC authentication to NuGet

    strategy:
      matrix:
        path: ${{fromJson(needs.release-please.outputs.paths_released)}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ format('refs/tags/{0}', fromJSON(needs.release-please.outputs.full)[format('{0}--tag_name', matrix.path)]) }}

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Install RepoCtl
        run: |
          dotnet tool install --global Altinn.Authorization.RepoCtl --version "${{ env.repoctlVersion }}"
          
          repoctl --version

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ format('release-{0}', fromJSON(needs.release-please.outputs.full)[format('{0}--id', matrix.path)]) }}
          path: artifacts

      - name: NuGet login
        id: nuget-login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        with:
          user: ${{ vars.NUGET_USER }}

      - name: Publish to NuGet
        env:
          NUGET_APIKEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
          FILES_GLOB: artifacts/**/*.nupkg
        run: |
          repoctl nuget publish "${FILES_GLOB}" -- --api-key "${NUGET_APIKEY}" --source "https://api.nuget.org/v3/index.json"
